spring.datasource.url=jdbc:mysql://metro.proxy.rlwy.net:22634/railway
spring.datasource.username=root
spring.datasource.password=tYwnphibcmaEwtjEVSBMXWWBxLeEDwEO

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}