spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}

ors.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImQ1N2ExY2VlNWMwMzQxYjU5YjE1ODEyNzllMDc2ZDMzIiwiaCI6Im11cm11cjY0In0=

